name: Gemini AI Code Reviewer (Flutter)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai_review:
    name: AI Code Review
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout source code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r scripts/requirements.txt

      - name: 🤖 Run Gemini AI Reviewer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: python scripts/ai_review.py
